### ISSUE TITLE
chore: updated readme with marketing targeted to functional programmers

### ISSUE THREAD

**Issue by dzmitry-lahoda** [elastio/bon#112]
> bon is a Rust crate for generating compile-time-checked builders for functions and structs.

builder are fine, but for many they bring negative connotation. 

but in languages, specifically F#, but guess many others, there are notions of `partial application` and `named parameters`. 

so basically bon is efficient way to implement these (there are failed attempts in Rust to do so).

so can improve search ability and appreciation of bon by:

 > bon is a Rust crate for generating compile-time-checked builders for functions, methods and structs,
>  idiomatic partial application, optional and named parameters for functions and methods

**Comment by Veetaha** [comment]
I'm fine with this change to Readme. I just tried to keep it simple for those beginner Rust developers, but I see people often asking questions like "why is it useful? does it support optional parameters", so I guess this change is for the better. 

Although, I have to note that partial application in the current state of `bon` is useful only in the patterns of conditional building at most.

**Comment by dzmitry-lahoda** [comment]
> I have to note that partial application in the current state of bon is useful only in the patterns of conditional building at most. The type signature of the partial builder is not stable yet, so partial application is useful only in a local scope.

Local scope is fine.

My case is proptest data builder or  setup for fuzzying or some ddos bot builder.

There whole frameworks build on that, like zio or https://effect.website/ . So it may still be useful.

For production case may appear to be HTTP, when need to negotiate content type or route depending on headers.

If there are chances `bon` builder will get public type at any point, than README is fine and future proof.

**Comment by Veetaha** [comment]
> ddos bot builder

What is the ddos target?

**Comment by dzmitry-lahoda** [comment]
> What is the target of ddos?

In order to try to stress/load test services, need to produce a lot of values which penetrate it functional deeply. For this need to use some input data builder to build reasonable inputs.
