### ISSUE TITLE
Set default of field to make it optional without Option

### ISSUE THREAD

**Issue by tontinton** [elastio/bon#119]
This will allow:

```
#[builder]
struct Test {
  #[builder_default=true]
  a: bool
}
```

Also for functions.

Exact syntax can be changed, doesn't really matter.

**Comment by Veetaha** [comment]
Hi, thank you for creating the issue! If you are looking for an attribute that makes the member optional, then there is such an attribute. It's called [`#[builder(default)]`](https://elastio.github.io/bon/reference/builder#default).

If you have any ideas how to improve its discoverability, I'd be happy to hear them 🐱

**Comment by cablehead** [comment]
I found this one easy to discover in the docs, fwiw

**Comment by Veetaha** [comment]
@tontinton see my comment https://github.com/elastio/bon/issues/119#issuecomment-2337546162, if that answers you question then close the issue.

I'll close the issue myself If I won't receive feedback from @tontinton

**Comment by tontinton** [comment]
oh ok thanks, I just missed it in the docs
