### ISSUE TITLE
chore: please make unstable truly unstable

### ISSUE THREAD

**Issue by dzmitry-lahoda** [elastio/bon#128]
currently unstable tests on 2 years old version of rust, it is wrong. 2 years version of rust is not unstable anymore - i would say that version does not exist and testing on is dummy stub (so it tests nothing at all).

**Comment by Veetaha** [comment]
The `test-unstable` tests run against the latest beta and nightly versions. See the [logs here](https://github.com/elastio/bon/actions/runs/10820903525/job/30021883957?pr=118#step:3:164). Could you elaborate?

**Comment by dzmitry-lahoda** [comment]
![image](https://github.com/user-attachments/assets/097197da-5299-4699-9a52-23edb3f9e6f3)

**Comment by dzmitry-lahoda** [comment]
```
rust-version = "1.59.0"
```
so bon-macro is tested with old version of rust, not nightly/beta.

so not sure why limit macro to old version so too (it runs on dev machine with for sure has compiler not 2 years old).

it is clear why `bon` crate so.

**Comment by Veetaha** [comment]
It's just a clippy lint called [`clippy::incompatible_msrv`](https://rust-lang.github.io/rust-clippy/master/index.html#/incompatible_msrv). The jobs still test against latest beta/nightly

**Comment by Veetaha** [comment]
The [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field in Cargo.toml declares the minimum required version of rustc for this library to compile. Given that people often upgrade their rust toolchain lazily libraries have to support older compiler versions if they want to support projects with older rustc versions

**Comment by dzmitry-lahoda** [comment]
For stable version fine to support old. No problem. 
So still problem.  Was Debian that Linux distro dicussed to have old version of Rust? Debian 11 LTS 1.48 rust. Next current Debian LTS is 1.63. Why not 1.48 than ? Because 1.57 will not compile right? Or 1.63? Or other target Linux system was used?

For unstable version, that weird. Considering 1.57 version to be `unstable` is weird. It does not makes any sense. Is there any prominent crate doing that?

**Comment by dzmitry-lahoda** [comment]
I mean fine to compile stable version of bon with rust target to be 1.57. But compiling unstable version of bon with rust target 1.57 does not have any sence...

**Comment by Veetaha** [comment]
bon must always comply with 1.59 MSRV no matter what version of toolchain is used. There is no exception for the unstable toolchain

**Comment by Veetaha** [comment]
I don't understand what change you propose, and why

**Comment by Veetaha** [comment]
I assume you  confuse unstable toolchain and "unstable" cargo features flag, which absolutely have nothing in common. The feature flag is just a marker for the user to sign the contract that bon may break the API of getters attributes in patch releases. And doesn't my intention with that feature flag was to check for it's presence in the validation method of parameters before allowing the usage of builder(getter).

See my PR comment. I said nothing about `#[cfg()]` all over the implementation

**Comment by Veetaha** [comment]
This is following the similar approach of clap https://github.com/clap-rs/clap/blob/df1efca03509f736e26d2f16766b7ea06acc3ecf/Cargo.toml#L169

**Comment by dzmitry-lahoda** [comment]
installed 1.59 rust, it fails 
```
Updating crates.io index
error: failed to select a version for the requirement `syn = "^2.0.56"`
candidate versions found which didn't match: 2.0.56, 2.0.55, 2.0.54, ...
location searched: crates.io index
required by package `bon-macros v2.2.1 (/home/dz/github.com/elastio/bon/bon-macros)`
```

so not clear at all what currently checked, but for sure no that specific linuxes with old version of rust can use bon macro. they cannot use bon macro using rust compiler version of 1.59.

**Comment by Veetaha** [comment]
They can, they just need to use lower versions of dependencies. Just take a look at how `test-msrv.sh` works:
https://github.com/elastio/bon/blob/3217b4b0349f03f0b2a5853310f420c5b8b005a7/scripts/test-msrv.sh#L35-L38

**Comment by dzmitry-lahoda** [comment]
> I didn't ask to put #[cfg(feature = "unstable")] all over the implementation, I meant a simple
> if !cfg!(feature = "unstable") && self.getter.is_some() 


@Veetaha not sure I get that. So you propose to have attribute to be available to put by users, but when macro generates code it just ignores it? Is not that bad? I supposed if get does not work it should not be available to put as macro attribute by user?

**Comment by Veetaha** [comment]
> just ignores it

No, the macro must return an error. See the `bail!(...)` inside of the if?

**Comment by dzmitry-lahoda** [comment]
> unstable-getters

why not singular getter? so attribute name equals feature? why it is unstable when it will be build on stable super old rust? or why it is unstable needed if it is behind feature get as has one and only one impl possible (not so much can think for getter unless whole gen to be changed - but than whole bon is unstable)?

**Comment by dzmitry-lahoda** [comment]
> No, the macro must return an error. See the bail!(...) inside of the if?

would not rust suggest option to type that field and than error during compilation in this case? how to ensure there is not suggestion to user to type `getter` if feature is off?

**Comment by Veetaha** [comment]
There are no completions in IDEs for proc macro attributes (except for some manual hacks that I did, which are limited and don't cover member-level attributes).
