### ISSUE TITLE
make this the official song of the project

### ISSUE THREAD

**Issue by atillabirer** [elastio/bon#140]
[https://www.youtube.com/watch?v=iLDHdYQ5vEw](url)

**Comment by Veetaha** [comment]
Hi, if there'd ever be an official song for this crate, it'd definitely be something family friendly 🐈. Maybe something related to candies 🍬 or the [Sweetie Drops](https://mlp.fandom.com/wiki/Sweetie_Drops) (original inspiration for the crate name and icon).

This one doesn't fit the theme unfortunately, but anyway, thank you for the suggestion 🐱
