### ISSUE TITLE
Possibly shorter struct builder method chain?

### ISSUE THREAD

**Issue by musjj** [elastio/bon#167]
The current struct builder method chain looks like this:

```rust
Project::builder()
    .name("Bon")
    .description("Awesome crate 🐱")
    .path("/path/to/your/heart")
    .build();
```

Might be controversial, but I wonder if it can be shortened by also putting all the field methods into the inherent impls and have it initiate the builder, like this:

```rust
Project::name("Bon")
    .description("Awesome crate 🐱")
    .path("/path/to/your/heart")
    .build();
```

So now you can start the builder and fill in the first chosen field with one call. What do you think?

**Comment by Veetaha** [comment]
Hi, this syntax is possible to achieve like this, however, you need to choose a specific field that you'd like to be the in the starting function ([start_fn](https://bon-rs.com/reference/builder#start-fn-1)):

```rust
use bon::Builder;
use std::path::PathBuf;

#[derive(Builder)]
#[builder(on(_, into), start_fn = name)]
struct Project {
    #[builder(start_fn)]
    name: String,
    description: String,
    path: PathBuf,
}

Project::name("Bon")
    .description("Awesome crate 🐱")
    .path("/path/to/bon")
    .build();
```

Is this what you are looking for, or you'd like to have multiple starting functions per each field? The latter looks like an overkill to me, but once 3.0 will be released it will be possible to write such functions manually (since the signature of the type builder will become stable).

**Comment by Veetaha** [comment]
Moreover, you can also move some members into the finishing function, and have the syntax like this, although I recommend working on better naming of the starting/finishing functions to make it clear that the start/finish the building process:

```rust
use bon::Builder;
use std::path::PathBuf;

#[derive(Builder)]
#[builder(on(_, into), start_fn = name, finish_fn = path)]
struct Project {
    #[builder(start_fn)]
    name: String,

    #[builder(finish_fn)]
    path: PathBuf,

    description: String,
}

Project::name("Bon")
    .description("Awesome crate 🐱")
    .path("/path/to/bon");
```

**Comment by musjj** [comment]
Oh wow thank you, didn't know you can do that. It's really amazing how flexible this library is :heart_eyes:

I think this covers all my use-cases, so I'm closing this!

**Comment by musjj** [comment]
Just another quick question, can you rename the `start_fn` in free functions? https://bon-rs.com/reference/builder#start-fn

I tried this but it doesn't work:

```rust
pub struct FooBar {
    ...
}

#[bon]
impl FooBar
{
    #[builder(start_fn = renamed)] // <-- doesn't work
    pub fn new(#[builder(start_fn)] foo: String) {
        ...
    }
}
```

Will this be possible with 3.0?

**Comment by Veetaha** [comment]
You can rename the method itself. `fn new -> renamed`:

```rust
pub struct FooBar {
    ...
}

#[bon]
impl FooBar
{
    #[builder]
    pub fn renamed(#[builder(start_fn)] foo: String) {
        ...
    }
}
```

There will be changes to start_fn in 3.0 that allow placing it on functions, but for a different purpose ([see the docs here](https://github.com/elastio/bon/blob/feat/more-docs-for-v3/website/reference/builder/top-level/start-fn.md#exposing-original-function), they aren't published to the website yet).
