### ISSUE TITLE
Generic type for an incomplete builder?

### ISSUE THREAD

**Issue by rollo-b2c2** [elastio/bon#21]
Appreciate this might be quite difficult to do:

If you want to pass around a builder you have to specify the state of the builder:

```rust
#[bon::builder]
pub struct T {
    a: usize,
    b: usize
}

fn a() -> TBuilder<(bon::private::Set<usize>, bon::private::Set<usize>)> {
    T::builder()
        .a(1)
        .b(2)
}

let var = a1();
var.build();

let var = a2().b(2);
var.build();
```

For complete structs it would make sense to type alias completeness to

```rust
type TBuilderValid = (bon::private::Set<usize>, bon::private::Set<usize>);
```

However what would be really useful would be some generic way of passing incomplete builders around. 

### A note for the community from the maintainers

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the maintainers with prioritizing it. You may add a comment describing your real use case related to this issue for us to better understand the problem domain.

**Comment by Veetaha** [comment]
> However what would be really useful would be some generic way of passing incomplete builders around.

Indeed. right now the builder-type signature is unstable. You can see that it references types from a `#[doc(hidden}]` internal module `bon::private`.

Unfortunately, I don't see any good syntax to expose the type states of the builder. As you can see today the builder's `__State` generic parameter expects a tuple that mentions the states of every member in order. This means the signature is positional. There is no clear association of tuple items with the member names that they correspond to syntactically.

Also, when specifying the type state for the builder one needs to always specify states for **all** members. This is very-very inconvenient.

Another way to do this could be passing a dyn trait with the syntax `TBuilder>dyn BuilderState<Field1 = Set, Field2 = Unset, Field3 = Unset, Field4 = Optional>>`, but it requires you to specify values for all associated trait types.

I could think of something if default associated types in traits are stable https://github.com/rust-lang/rust/issues/29661.

**Comment by Veetaha** [comment]
> For complete structs it would make sense to type alias completeness to

I'm not sure if this is could be useful. One use case that I can think of is to prepare the parameters for a function without actually calling it and then storing the these parameters in the "complete" builder somewhere to lazily invoke the `.call()` method somewhere later. Is this your thinking as well?

If so, as a compromise solution `bon`'s codegen may be extended to give a type alias for such a "complete" builder. Note that the builder captures all the lifetimes and generic type/const parameters from the function and impl block (if is is under an impl block). These generic params need to be part of the "complete" builder type alias. This is already the case today for the "initial" builder state today though. That type name is kinda public, although not advertised in the docs.

**Comment by Veetaha** [comment]
Some more thoughts on this issue:

There isn't just one terminal state for the builder where you can call the finishing functions (`call()` or `build()`).

For example:

```rust
#[builder]
struct Foo {
    a: Option<String>,
    b: Option<String>,
}

// `FooBuilder<(Optional<Option<String>>, Optional<String>)>`
Foo::builder().build();

// `FooBuilder<(Set<Option<String>>, Optional<String>)>`
Foo::builder().a("a").build();

// `FooBuilder<(Optional<String>, Set<Option<String>>)>`
Foo::builder().b("b").build();

// `FooBuilder<(Set<Option<String>>, Set<Option<String>>)>`
Foo::builder().a("a").b("b").build();
```

In the generated code the terminal states a covered by the `#[doc(hidden)]` trait `IntoSet` which expresses the possibility of converting `Optional<Option<T>` into `Set<Option<T>`.

Here is how the generated impl block for the `build()` method looks like in this case:

```rust

    impl<__State: __FooBuilderState> FooBuilder<__State>
    where
        __State::A: bon::private::IntoSet<Option<String>>,
        __State::B: bon::private::IntoSet<Option<String>>,
    {
        #[doc = r" Finishes building and performs the requested action."]
        fn build(self) -> Foo {
            Foo {
                a: ::bon::private::IntoSet::into_set(self.__private_impl.a).into_inner(),
                b: ::bon::private::IntoSet::into_set(self.__private_impl.b).into_inner(),
            }
        }
    }
```

This means there is no single `"complete"` builder type state. So it's not possible to express it with just a single type alias. It'll probably need to be a trait:

```
trait TBuilderComplete {
     fn build(self) -> T;
}
```

And that impl block higher can be turned into this trait impl instead. Then we can make the trait name exposed from the generated code.

**Comment by Veetaha** [comment]
I've implemented a way to denote the incomplete builder type (with some members set).

See #145 for details. It should close this issue
