### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by Deaths-Door** [elastio/bon#23]
I'm interested in using your tool but it currently lacks support for Rust enums. I propose extending the macro to handle enums as well.

For unit enums, the macro could either ignore them or generate a dummy function. For example 
```rust 
impl $enum {
   fn $variant () {
      $enum :: $variant
   }
}
```

For unnamed enums, I'm unsure whether generating no code or implementing a default 'from' function for each variant is the best approach. For example 

```rust 
impl $enum {
    fn $variant (value : impl Into<$inner_field_type>) {
       $enum :: $variant ( value.into())
    }
}
```

For named enums, we create a builder struct, generate builder methods for each field, and modify the `finish_fn` to return the enum variant instead of the builder struct. Additionally, a `start_fn` would be generated to create a new builder instance from the enum. So 
```rust
impl $enum {
    fn $variant ()  -> #builder {
       #builder :: #inner_start_fn
    }
}
```

**Comment by Veetaha** [comment]
I haven't seen a need for enum builders on my experience. I'd like to know more about your use case and how builder for enum would solve it.

From my side I can tell that I have another good proc macro currently in a private repo that I use to generate `From<Variant>` implementations for enums plus various methods to downcast the enum into its variants.

Here is the snippet of its documentation:

---

 Derives various `From/TryFrom` conversions for the enum to its variants.
 Also adds the following methods for each variant:

 - `is_*            -> bool`
 - `as_*            -> Option<&T>`
 - `as_mut_*        -> Option<&mut T>`
 - `into_*          -> Option<T>`
 - `try_as_*        -> Result<&T>`
 - `try_as_mut_*    -> Result<&mut T>`
 - `try_into_*      -> Result<T>`
 - `unwrap_as_*     -> &T`
 - `unwrap_as_mut_* -> &mut T`
 - `unwrap_*        -> T`
 - `unwrap::<T>     -> T`
 - `unwrap_ref::<T> -> &T`
 - `unwrap_mut::<T> -> &mut T`
 ---
 
 Having such a macro allows you to avoid building enums directly. Instead you'd define enums as pure sum types, which you can create out of structs that derive builders.
 
 For example:
 
 ```rust
 use bon::builder;
 
#[derive(Sum)]
enum Foo {
     A(A),
     B(B),
} 

#[builder]
struct A {}

#[builder]
struct B {}

// Create the enum:

let enum_value: Foo = A::builder().build().into();
assert!(matches!(enum_value, Foo::A(_)));

let enum_value: Foo = B::builder().build().into();
assert!(matches!(enum_value, Foo::B(_)));
 ```

**Comment by Veetaha** [comment]
I'd try to avoid doing that and discuss alternative simpler approaches first like the one above with generating `From` implementations for enums. However, I'll leave some comments about the design currently proposed in the issue.

Drawing some inspiration from this PR into `typed-builder` is a good place to start: https://github.com/idanarye/rust-typed-builder/pull/129.

For example, there were some good points raised about naming of methods. Enums usually have methods named after variants to implement getters like `Result::ok` and `Result::err`. I'd probably think of having `Enum::builder()` method that returns a builder first which then has a method to start the construction of each variant.

**Comment by Veetaha** [comment]
> For instance, relying on methods like unwrap_a() can introduce potential error points , which a builder for each variant would solve.

That `unwrap_a()` method is a bit different story. It's a method on an enum that downcast it to the variant `A`. It panics if enum's current variant is something different. It's not actually related to the builder itself. I guess let's probably ignore that.

---

Another comment about your use case. Did you consider defining builders for your enums via methods?

For example:
```rust
use bon::bon;

enum Expression {
    Term,
    Custom,
    Number(u32),
    Binary {
        op: String,
        left: Box<Self>,
        right: Box<Self>,
    }
}

#[bon]
impl Expression {
     #[builder]
     fn binary(
         op: String,
         
         #[builder(into)]
         left: Box<Self>,
         
         #[builder(into)]
         right: Box<Self>,
     ) -> Self {
         Self::Binary { op, left, right }
     }
}

Expression::binary()
    .op("==")
    .left(Expression::Number(1))
    .right(Expression::Number(3))
    .build();
```

It is a bit more code to write, but it generates the builder that you'd like. This will let you have a builder for your enum without the need to go long-long route of designing and implementing builders for enums in `bon`.
