### ISSUE TITLE
Support default values for optional fields

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [elastio/bon#231]
Hi again :D,

I am opening this issue to request support for default values for optional fields. My use case involves defining fields as optional (`Option<T>`) while also assigning a default value. This is useful for scenarios where some fields can be left undefined but still have sensible defaults.

**Example Use Case:**

```rust
#[derive(Builder)]
struct Text {
    name: String,
    #[builder(default = Some(capitalize(&name)))]
    label: Option<String>,
}
```

Currently, handling such case would requires additional boilerplate code or might be not possible? (I gave it quick try and failed). It would be great if Bon natively supported this functionality.

I also have some challenges when I use `field` with default value like this:
```rust
#[derive(Builder)]
struct Text {
    #[builder(field = Some(capitalize(&name)))] // here I cannot use name value to construct the default value
    label: Option<String>,

    name: String,
}
```

### A note for the community from the maintainers

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the maintainers with prioritizing it. You may add a comment describing your real use case related to this issue for us to better understand the problem domain.

**Comment by Veetaha** [comment]
Hi, could you show an example of the builder API that you'd like to achieve?
I believe you could just do this:
```rust
#[derive(Builder)]
struct Text {
    name: String,
    #[builder(default = capitalize(&name))]
    label: String,
}
```

You need to define `label` as a regular `String`, and use [`#[builder(default = ...)]`](https://bon-rs.com/reference/builder/member/default) to make the field optional in the builder API. Is there any reason to keep the field as `Option<String>` in your case>

**Comment by MuhannadAlrusayni** [comment]
> Is there any reason to keep the field as Option<String> in your case?

Thank you for your question! 

The reason for keeping the field as `Option<String>` is to support flexibility in our SSR UI components crate, which is used by my team. Some components, such as `Text`, have an optional `label`. 

By default, the `label` is initialized as `Some(capitalize(&name))`, as the label often mirrors the `name` field but is capitalized. This default behavior ensures most use cases are streamlined without requiring extra input from the user.

However, we also allow users to opt out of using a label entirely. They can call a method like `maybe_label(None)` (or in my implementation, `no_label()` for convenience) to explicitly indicate that no label is needed. Here's an example of how this works:

```rust
Text::builder()
    .name("email")
    .no_label() // Or .maybe_label(None)
    .build()
```

This design provides flexibility while keeping sensible defaults for common use cases.

**Comment by Veetaha** [comment]
Note that `maybe_label(None)` will explicitly use the default value (specified via `#[builder(default = ...)]`), which is by design. `maybe_label(None)` is always equivalent to just not calling any setters `label/maybe_label` at all, which allows you to dynamically decide whether you want to use the default or not by passing an `Option<_>` value at runtime.

Thus, `maybe_label` won't set the `label` to `None` in the resulting `Text`, it will set it to `Some(capitilize(&name))` instead.

If you want to achieve the threestatae behavior of `explicit Some`, `explicit None`, `explicit/implicit default Some(capitilize(&name))`, you need to expose the nested `Option<Option<_>>` in the setters.

To do that we you can use [`#[builder(required)]`](https://bon-rs.com/reference/builder/member/required) to disable the special handling for `Option<_>` type, and the [`#[builder(default)]`](https://bon-rs.com/reference/builder/member/default) attribute to assign a custom default for it. 

```rust
#[derive(bon::Builder)]
struct Text {
    name: String,

    #[builder(required, default = Some(capitalize(&name)))]
    label: Option<String>,
    // In this case the following setters are generated:
    //
    // label(Option<String>) - never uses the default value. `None` means real `None` in the `label`
    // maybe_label(Option<Option<String>>) - here  `None` means the default value
    //                                       while Some(None) means the real `None` in the `label`
}

fn main() {
    // Here label is `Some("Hello")`
    let _ = Text::builder()
        .name("hello".to_string())
        .build();

    // Here label is `Some("world")`
    let _ = Text::builder()
        .name("hello".to_string())
        .label(Some("world".to_string()))
        .build();

    // Here label is `None`
    let _ = Text::builder()
        .name("Hello".to_string())
        .label(None)
        .build();

    // Here label is `Some("Hello")`
    let _ = Text::builder()
        .name("Hello".to_string())
        .maybe_label(None)
        .build();

    // Here label is `None`
    let _ = Text::builder()
        .name("Hello".to_string())
        .maybe_label(Some(None))
        .build();
}

fn capitalize(s: &str) -> String {
    "TODO: impl".to_owned()
}
```

**Comment by MuhannadAlrusayni** [comment]
What I am looking for is the following API:
- `fn label(String)`; overwrite the default value.
- `fn maybe_label(Option<String>)`;  overwrite the default value as well.

If none of these methods get called, it mean we want to use the default value.

If I want the default value I would not call `label`/`maybe_label`, if I want to set a label I would call `label("Hello")`, if I don't want label at all I would call `maybe_label(None)`.

**Comment by Veetaha** [comment]
> Is that possible ?

Yeah, it's possible to achieve with the [custom setters](https://bon-rs.com/guide/typestate-api/custom-methods#custom-setters). This has to use custom setters because otherwise the semantics of `maybe_{member}(None)` is already taken to mean the default value. However, you can write your custom setters

```rust
#[derive(bon::Builder)]
pub struct Text {
    name: String,

    #[builder(
        required,
        default = Some(capitalize(&name)),
        // Make the setters private under a different name. We'll define our own
        setters(vis = "", name = label_internal),
    )]
    label: Option<String>,
}

use text_builder::{IsUnset, SetLabel, State};

impl<S: State> TextBuilder<S> {
    pub fn label(self, label: String) -> TextBuilder<SetLabel<S>>
    where
        S::Label: IsUnset,
    {
        self.maybe_label(Some(label))
    }

    // `None` means the resulting label will be `None`. The default value can be used only if you don't call any setters
    pub fn maybe_label(self, label: Option<String>) -> TextBuilder<SetLabel<S>>
    where
        S::Label: IsUnset,
    {
        self.label_internal(label)
    }
}
```

**Comment by MuhannadAlrusayni** [comment]
Thanks, I'll give this try! for me this is more than enough since this case doesn't come very often in my codebase.

**Comment by Veetaha** [comment]
I'm confident the solution above should fit your use case. If not, feel free to reopen, create a new issue or message me on https://bon-rs.com/discord
