### ISSUE TITLE
`r#type` is not a valid identifier

### ISSUE THREAD

**Issue by rollo-b2c2** [elastio/bon#8]
```
#[builder]
struct {
    r#type: String
}
```

This doesn't work.  Can work around it by using serde rename, but it's a minor bug.

**Comment by Veetaha** [comment]
Thank you for the bug report! It was fixed in #9. A new patch version of the crate `1.0.1` with the fix was released.

**Comment by rollo-b2c2** [comment]
ty, slava ukraini
