### ISSUE TITLE
Add #[default]

### ISSUE THREAD

**Issue by beckend** [elastio/bon#83]
Where `T::Default`, unsure how to annotate it for a function.

**Comment by Veetaha** [comment]
Hi, thank you for creating the issue! If you are looking for an attribute that makes the argument for a function optional, then there is such an attribute. It's called `#[builder(default)]`. Here is an example of how it can be used:

```rust
use bon::builder;

#[builder]
fn greet_user(
    #[builder(default)] 
    level: u32,

    // The expression of type `&'static str` is automatically
    // converted to `String` here via `Into` thanks to `#[builder(into)].
    #[builder(into, default = "anon")]                                    
    name: String,

    // Any complex expression is accepted
    #[builder(default = bon::vec!["read"])] 
    permissions: Vec<String>,
) -> String {
    format!("Hello {name}! Your level is {level}, permissions: {permissions:?}")
}

let greeting = greet_user().call();

assert_eq!(greeting, "Hello anon! Your level is 0, permissions: [\"read\"]");
```


Here are the [docs for this attribute in the reference](https://elastio.github.io/bon/reference/builder#default). If you found it hard to find in the docs, and you have any ideas how to improve its discoverability, I'd be happy to hear them 🐱

**Comment by beckend** [comment]
I see, thanks!
