### ISSUE TITLE
`bon` 3.0 wishlist (far, maybe never accepted breaking changes)

### ISSUE THREAD

**Issue by Veetaha** [elastio/bon#85]
⚠️ There is no particular plan for a new major release right now! This issue exists just to record some thoughts on the things that we may potentially break in the far future, or we maybe we won't. They aren't as critical, or maybe even arguable, thus we don't have any immediate plans for a new major release yet.

Here are some items that we may consider doing as part of the `bon` 3.0 major release. These are specifically breaking changes that we can't afford to do as part of a minor/patch release.

1. Reconsider making the generated `Builder` type private (unexposed) by default. E.g. the builder type should contain `__` as a prefix and be `#[doc(hidden)]` to effectively make it an "anonymous type". The reason is to hide it from the `rustdoc` output by default because its type signature is rather complex and noisy, such that it's unlikely people may read its docs.
2. Restrict the relative ordering of positional members, regular named members, and skipped members

### Verdict

1. **Rejected.** The rustdoc output is now much cleaner with the https://github.com/elastio/bon/pull/145. There are no noisy generics - only a single builder type state generic parameter
2. **Rejected.** I don't think restricting more than what's already limited today makes sense (the order of start_fn -> finish_fn -> all other members). The order of members should only represent the order in which variables appear in scope of the `skip/default` expressions, and today's order is completely consistent with that.

**Comment by dzmitry-lahoda** [comment]
Allow for groups and conflicts like in `clap`.  Also saw something like that in compile time builder, cannot find it now, as I recall it needed some solver to be run  at build time.

These features allow to state:
- if this field was set, than some other field(s) must be set
- if this field was set, than some other field(s) cannot be set

I have my manually crafted builders and do:
-  start from most stable input (most stable inputs are to the left in function parameters, allows for partial application to be effective), doubt it can be automated - hence forever manual builder. interestingly, bon helps partially with this basically adding partial application and named parameters somewhat into Rust (like it is in F#) 
- do most limiting input first. so if one group field sets most limits to reduce source code of generated types, they must be set first (not all methods available in consumer of builder at once). this can be optimization problem of groups/conflicts - find group constraints which limit type states most.
- not sure if that possible, if field is elementary enum, allow named method to set field value for that. enum has variants Bar and Foo, and stored in field type so add method to set type_foo and type_bar. Useful with group feature.

**Comment by dzmitry-lahoda** [comment]
Allow for groups and conflicts like in clap. Also saw something like that in compile time builder, cannot find it now, as I recall it needed some solver to be run at build time.

These features allow to state:

- if this field was set, than some other field(s) must be set
- if this field was set, than some other field(s) cannot be set

I have my manually crafted builders and do:
- start from most stable input (most stable inputs are to the left in function parameters, allows for partial application to be effective), doubt it can be automated - hence forever manual builder. interestingly, bon helps partially with this basically adding partial application and named parameters somewhat into Rust (like it is in F#)
- do most limiting input first. so if one group field sets most limits to reduce source code of generated types, they must be set first (not all methods available in consumer of builder at once). this can be optimization problem of groups/conflicts - find group constraints which limit type states most.
- not sure if that possible, if field is elementary enum, allow named method to set field value for that. enum has variants Bar and Foo, and stored in field type so add method to set type_foo and type_bar. Useful with group feature.

**Comment by Veetaha** [comment]
Hi @dzmitry-lahoda, this issue is specifically about breaking changes. What you proposed is not a breaking change, therefore I've extracted it into #110.

**Comment by cksac** [comment]
The function builder required `finish_fn`, which may not look good in method chaining use case.
Not sure can we have option generate only two variant, `<fn>`, `<fn>_with` without need to call `finish_fn`?

```rust
use bon::builder;

#[builder]
fn greet(name: &str, level: Option<u32>) -> String {
    let level = level.unwrap_or(0);

    format!("Hello {name}! Your level is {level}")
}

// required fields into positional arguments
let greeting = greet("Bon");
assert_eq!(greeting, "Hello Bon! Your level is 0");

// uss <fn>_with for provide optional fields
let greeting = greet_with("Bon", |b| { b.level(24); });
assert_eq!(greeting, "Hello Bon! Your level is 24");


struct Tensor {}

#[bon]
impl Tensor {
    pub fn new() -> Self {
        Tensor{}
    }

    #[builder]
    fn op1(&self, x: &str, level: Option<&str>) -> Tensor {
        Tensor{}
    }

    #[builder]
    fn op2(&self, y: &str, level: Option<&str>) -> Tensor {
        Tensor{}
    }
}


let tensor = Tensor::new();
tensor.op1("x").op2("y");
tensor.op1_with("x", |b| b.level(2)).op2("y");
```

verse existing

```rust
let tensor = Tensor::new();
tensor.op1("x").call().op2("y").call();
tensor.op1("x").level(2).call().op2("y").call();
```

**Comment by Veetaha** [comment]
Hey @cksac the requirement of the `finish_fn` call can not be easily alleviated because this method is the one that converts `TensorBuilder` into `Tensor`. Bon generates the builder that is designed with extensibility in mind. For example, if you add more optional fields to the `Tensor` in the future, then how will the builder know if you intend to set the optional fields or it's already time to convert into the `Tensor` object?

See an alternative feature that may solve this problem. I have a draft PR for it https://github.com/elastio/bon/pull/125 which you can test for yourself (the release target is somewhere by the end of this week). It allows you to pass arguments into the start_fn and finish_fn.

I can't see a practical application in the example with the `Tensor` that you shown, so I'll show my example with the `Point` struct. I hope it'll help you to apply this idea to your use case with a `Tensor` or whatever else use case you have.

```rust
use bon::builder;

#[builder]
fn greet(#[builder(pos = start_fn)] name: &str, level: Option<u32>) -> String {
    let level = level.unwrap_or(0);

    format!("Hello {name}! Your level is {level}")
}

let greeting = greet("Bon").call();
let greeting = greet("Bon").level(24).call();


#[derive(bon::Builder)]
#[builder(start_fn = x, finish_fn = y)]
struct Point {
    #[builder(pos = start_fn)]
    x: u32,

    #[builder(pos = finish_fn)]
    y: u32,
}

let _ = Point::x(1).y(2);
```

@cksac let me know if this solves (or at least helps with) your problem

**Comment by Veetaha** [comment]
One more trick. If you want to avoid calling the finishing method, just make the finishing method accept one of the required fields (which although forces the caller to pass the value for this member as the last one in the chain), and then add setters for optional fields. 

In this example, after the `.arg2(2)` call the `Example` object was already built with all optional fields set to `None`:

```rust
use bon::Builder;

#[derive(Builder)]
#[builder(finish_fn = arg2)]
struct Example {
    arg1: i32,

    #[builder(pos = finish_fn)]
    arg2: i32,

    #[builder(skip)]
    optional_1: Option<i32>,

    #[builder(skip)]
    optional_2: Option<i32>,
}

impl Example {
    fn optional_1(mut self, value: i32) -> Self {
        self.optional_1 = Some(value);
        self
    }

    fn optional_2(mut self, value: i32) -> Self {
        self.optional_2 = Some(value);
        self
    }
}

let _ = Example::builder().arg1(1).arg2(2).optional_1(99);
```

I'll probably need to document all these patterns in the "Patterns" section of the docs

**Comment by cksac** [comment]
I think we can generate two function variants from original function which use the generate builder? like
```rust
use bon::builder;

#[builder]
fn greet(name: &str, level: Option<u32>) -> String {
    let level = level.unwrap_or(0);
    format!("Hello {name}! Your level is {level}")
}

// generated helper functions
fn _greet(name: &str) -> String {    
    greet().name(name).call()
}

fn _greet_with<F>(name: &str, set: F) -> String 
where F: FnOnce(GreetBuilder) 
{
    let builder = greet().name(name);
    set(builder);
    builder.call()
}
```

**Comment by cksac** [comment]
with custom finish_fn, it seems even harder to read?
```rust
tensor
    .op1("x") // TensorOp1Builder
    .level(24) // Tensor, finish_fn of op1
    .op2("y") // TensorOp1Builder
    .call() // Tensor, finish_fn of op2
```
compare to
```rust
    tensor
    .op1("x") // Tensor    
    .op2_with("y",  |b| b.level(2)) // Tensor
```

**Comment by Veetaha** [comment]
As for me the closure syntax is harder to read and compose because now your code is nested inside of anther function. You can no longer use the [partial builder pattern](https://elastio.github.io/bon/guide/patterns/conditional-building#shared-partial-builder) and you can't do an early return from the function. 

See the comment https://github.com/idanarye/rust-typed-builder/issues/66#issuecomment-1114353926 from the author of `typed-builder` which explains why closure syntax is bad.

Could elaborate on your real use case where you'd like the syntax proposed here? I'd like to understand the logic behind the builder in your case to better understand the problem domain.

**Comment by cksac** [comment]
![image](https://github.com/user-attachments/assets/c8e4591b-dd79-471a-9429-7de947b0c67f)
I use a lot of method chaining in a ML lib, the purpose enhancement is for readability.
you can see below code, the builder type returned in between the method chain, I can't tell which call create a Tensor without IDE's help, right?
```rust
tensor
    .op1("x") // TensorOp1Builder
    .level(24) // Tensor, finish_fn of op1
    .op2("y") // TensorOp2Builder
    .call() // Tensor, finish_fn of op2
```

**Comment by Veetaha** [comment]
In the example shown here the existing API already looks nice. Every method returns a `Tensor` on every step of an operation. Every operation takes only a single parameter. So I don't see a need for using `bon` in this case. `bon` is useful if your method takes 3 or more parameters (or at least it can grow in the future to accept more parameters).

Basically, as I understand your `Tensor` API it's more of a "combinators" combination where you can also apply the same combinators several times (like there is `max_pool2D` applied several times. While `bon` constraints the caller to never call the same setter twice.

**Comment by cksac** [comment]
The example I show did't apply bon yet, and some ops will take more than 1 args.
btw, I am propose the enhance for function builder only not struct.

**Comment by Veetaha** [comment]
If you'd mix a builder in the middle of this combinators layering(especially, if you remove the explicit `finish_fn` call), then it indeed becomes hard to distinguish where one combinator statrs and ends:

```rust
tensor
    .operation_1(some_arg, some_arg2) // -> Builder
    .optional_param_to_operation("foo") // -> Builder
    .call() // -> Tensor (now that we've set all optional params, call the next combinator) ...
    .operation_2(some_arg, some_other_arg) // -> Builder
```

The problem that you can add optional parameters requires an explicit `finish_fn` call. I don't see a way around it.

The closure syntax looks unpretty, and I would like to avoid generating multiple variants of the same API and setters if possible to keep compile times lower and cognitive overhead lower as well (when there is just one way to do something, it makes your code structure more consistent)

**Comment by Veetaha** [comment]
Btw, in the example here:

```rust
impl Tensor {
    #[builder]
    fn op1(&self, x: &str, level: Option<&str>, op2: Option<&'static str>) -> Tensor {
        Tensor{}
    }

    #[builder]
    fn op2(&self, y: &str, level: Option<&str>) -> Tensor {
        Tensor{}
    }
}


let tensor = Tensor::new();
tensor.op1("x").op2("y");
tensor.op1_with("x", |b| b.level(2)).op2("y");
```

The `tensor.op1("x").op2("y")` can't possibly work because there is ambiguity: "are you trying to set the parameter named `op2` in the `op1` method, or are you already finished and want to call the `op2` method on `Tensor`?"

Same thing with 
```rust
tensor.op1_with("x", |b| b.level(2)).op2("y");
```
Is that `op2` a parameter or a method on `Tensor`? The compiler has no way to know at which point it should convert the builder into a `Tensor`.

**Comment by cksac** [comment]
here is a working example showing what I want to achieve. And comparison of two style.
for implementation, I think we can allow a config to generate one of fn builder to avoid breaking change.

```rust
use bon::bon;

struct Tensor {}

#[bon]
impl Tensor {
    pub fn new() -> Self {
        Tensor {}
    }

    #[builder]
    fn _sum(
        &self,
        dims: &[i64],
        #[builder(default)] keep_dim: bool,
        #[builder(default)] mean: bool,
    ) -> Tensor {
        Tensor {}
    }

    // GENERATED, all required parameters are positional
    fn sum(&self, dims: &[i64]) -> Tensor {
        self._sum().dims(dims).call()
    }

    // GENERATED, all required parameters are positional, with clouser to set optional parameters
    fn sum_with<F, __KeepDim, __Mean>(&self, dims: &[i64], set: F) -> Tensor
    where
        for<'__f1, '__f2> F: FnOnce(
            TensorSumBuilder<
                '__f1,
                '__f2,
                (
                    ::bon::private::Set<&'__f1 [i64]>,
                    ::bon::private::Unset<::bon::private::Optional>,
                    ::bon::private::Unset<::bon::private::Optional>,
                ),
            >,
        ) -> TensorSumBuilder<
            '__f1,
            '__f2,
            (::bon::private::Set<&'__f1 [i64]>, __KeepDim, __Mean),
        >,
        __KeepDim: bon::private::IntoSet<Option<bool>, TensorSumBuilder__keep_dim>,
        __Mean: ::bon::private::IntoSet<Option<bool>, TensorSumBuilder__mean>,
    {
        let b = self._sum().dims(dims);
        set(b).call()
    }

    #[builder]
    fn _mean(&self, dims: &[i64], #[builder(default)] keep_dim: bool) -> Tensor {
        Tensor {}
    }

    fn mean(&self, dims: &[i64]) -> Tensor {
        self._mean().dims(dims).call()
    }

    fn mean_with<F, __KeepDim>(&self, dims: &[i64], set: F) -> Tensor
    where
        for<'__f1, '__f2> F: FnOnce(
            TensorMeanBuilder<
                '__f1,
                '__f2,
                (
                    ::bon::private::Set<&'__f1 [i64]>,
                    ::bon::private::Unset<::bon::private::Optional>,
                ),
            >,
        ) -> TensorMeanBuilder<
            '__f1,
            '__f2,
            (::bon::private::Set<&'__f1 [i64]>, __KeepDim),
        >,
        __KeepDim: ::bon::private::IntoSet<Option<bool>, TensorMeanBuilder__keep_dim>,
    {
        let b = self._mean().dims(dims);
        set(b).call()
    }
}

fn main() {
    let t = Tensor::new();

    // exiting
    let output = t
        ._sum()
        .dims(&[1, 2])
        .keep_dim(true)
        .mean(false)
        .call()
        ._mean()
        .dims(&[1])
        .keep_dim(true)
        .call()
        ._sum()
        .dims(&[1])
        .call()
        ._mean()
        .dims(&[1])
        .call();

    // proposed
    let output = t
        .sum_with(&[1, 2], |b| b.keep_dim(true).mean(false))
        .mean_with(&[2], |b| b.keep_dim(true))
        .sum(&[1])
        .mean(&[1]);
}
```

**Comment by Veetaha** [comment]
@cksac how about this? What if `bon` generates a `From<TBuilder> for T` for you, so you can then implement such API with the closure manually if you want. Right now such impl isn't generated, but it's possible to add, here is how it looks:

```rust
struct Tensor {}

// Define optional parameters in a struct
#[derive(bon::Builder)]
struct SumOptionalParams {
    #[builder(default)]
    keep_dim: bool,
    
    #[builder(default)]
    mean: bool,
}

// This impl will be generated by `bon::Builder` (maybe by default, or maybe opt-in via an attribute config)
impl<KeepDim, Mean> From<SumOptionalParamsBuilder<(KeepDim, Mean)>> for SumOptionalParams
where
    KeepDim: bon::private::IntoSet<Option<bool>, SumOptionalParamsBuilder__keep_dim>,
    Mean: bon::private::IntoSet<Option<bool>, SumOptionalParamsBuilder__mean>,
{
    fn from(builder: SumOptionalParamsBuilder<(KeepDim, Mean)>) -> Self {
        builder.build()
    }
}

impl Tensor {
    pub fn new() -> Self {
        Tensor {}
    }

    fn sum<T: Into<SumOptionalParams>>(
        &self,
        dims: &[i64],
        optional: impl FnOnce(SumOptionalParamsBuilder) -> T,
    ) -> Tensor {
        let params: SumOptionalParams = optional(SumOptionalParams::builder()).into();
        Tensor {}
    }
}

let t = Tensor::new()
    .sum(&[1, 2], |b| b.keep_dim(true).mean(false));
```
This code compiles with the current version of `bon`. The thing that's lacking is that `From<TBuilder> for T` impl.

Or maybe it's better to have a trait that could be used as a geneiruc bound for the return type of the closure smth like

```rust
trait Builder {
    type Output;
    
    fn build() -> Self::Output;
}
```
but I'm not sure about it yet.

**Comment by cksac** [comment]
@Veetaha , with `From<TBuilder> for T`, still a lot of work at user end, also the original function need to rewrite..
I am appreciate if `bon` can generate all from original function definition. That's why I post in this issue `bon 3.0 wishlist` :)

**Comment by Veetaha** [comment]
I don't think there is anything `3.0` to this feature, because it doesn't require a breaking change, I created a separate issue https://github.com/elastio/bon/issues/127 for this. I'm fine with having a `From<TBuilder> for T` syntax, but I'm currently not convinced that `bon` should generate the whole closure syntax because I don't have evidence of broad demand for this feature.

**Comment by Veetaha** [comment]
Closing this in favour of https://github.com/elastio/bon/issues/156
